/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type AccountType = (typeof AccountType)[keyof typeof AccountType];
export declare const AccountType: {
    readonly asset: "asset";
    readonly liability: "liability";
    readonly equity: "equity";
    readonly revenue: "revenue";
    readonly expense: "expense";
};
//# sourceMappingURL=accountType.d.ts.map