/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Get dashboard financial summary
 */
export const GetDashboardSummaryResponse = zod.object({
  totalReceivable: zod.number(),
  totalPayable: zod.number(),
  cashBalance: zod.number(),
  overdueInvoices: zod.number(),
  overdueBills: zod.number(),
  totalRevenue: zod.number(),
  totalExpenses: zod.number(),
  netProfit: zod.number(),
});

/**
 * @summary Monthly cash flow for the last 6 months
 */
export const GetCashFlowResponseItem = zod.object({
  month: zod.string(),
  inflow: zod.number(),
  outflow: zod.number(),
  net: zod.number(),
});
export const GetCashFlowResponse = zod.array(GetCashFlowResponseItem);

/**
 * @summary Aged receivables summary
 */
export const GetAgedReceivablesResponse = zod.object({
  current: zod.number(),
  days1to30: zod.number(),
  days31to60: zod.number(),
  days61to90: zod.number(),
  over90: zod.number(),
  total: zod.number(),
});

/**
 * @summary Aged payables summary
 */
export const GetAgedPayablesResponse = zod.object({
  current: zod.number(),
  days1to30: zod.number(),
  days31to60: zod.number(),
  days61to90: zod.number(),
  over90: zod.number(),
  total: zod.number(),
});

/**
 * @summary List all contacts
 */
export const ListContactsQueryParams = zod.object({
  type: zod.enum(["customer", "supplier", "both"]).optional(),
  search: zod.coerce.string().optional(),
});

export const ListContactsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string().optional(),
  phone: zod.string().optional(),
  type: zod.enum(["customer", "supplier", "both"]),
  address: zod.string().optional(),
  city: zod.string().optional(),
  country: zod.string().optional(),
  taxNumber: zod.string().optional(),
  accountNumber: zod.string().optional(),
  isActive: zod.boolean(),
  createdAt: zod.coerce.date(),
});
export const ListContactsResponse = zod.array(ListContactsResponseItem);

/**
 * @summary Create a contact
 */
export const CreateContactBody = zod.object({
  name: zod.string(),
  email: zod.string().optional(),
  phone: zod.string().optional(),
  type: zod.enum(["customer", "supplier", "both"]),
  address: zod.string().optional(),
  city: zod.string().optional(),
  country: zod.string().optional(),
  taxNumber: zod.string().optional(),
  accountNumber: zod.string().optional(),
});

/**
 * @summary Get a contact
 */
export const GetContactParams = zod.object({
  id: zod.coerce.number(),
});

export const GetContactResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string().optional(),
  phone: zod.string().optional(),
  type: zod.enum(["customer", "supplier", "both"]),
  address: zod.string().optional(),
  city: zod.string().optional(),
  country: zod.string().optional(),
  taxNumber: zod.string().optional(),
  accountNumber: zod.string().optional(),
  isActive: zod.boolean(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update a contact
 */
export const UpdateContactParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateContactBody = zod.object({
  name: zod.string(),
  email: zod.string().optional(),
  phone: zod.string().optional(),
  type: zod.enum(["customer", "supplier", "both"]),
  address: zod.string().optional(),
  city: zod.string().optional(),
  country: zod.string().optional(),
  taxNumber: zod.string().optional(),
  accountNumber: zod.string().optional(),
});

export const UpdateContactResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string().optional(),
  phone: zod.string().optional(),
  type: zod.enum(["customer", "supplier", "both"]),
  address: zod.string().optional(),
  city: zod.string().optional(),
  country: zod.string().optional(),
  taxNumber: zod.string().optional(),
  accountNumber: zod.string().optional(),
  isActive: zod.boolean(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete a contact
 */
export const DeleteContactParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Get financial summary for a contact
 */
export const GetContactSummaryParams = zod.object({
  id: zod.coerce.number(),
});

export const GetContactSummaryResponse = zod.object({
  contactId: zod.number(),
  totalInvoiced: zod.number(),
  totalPaid: zod.number(),
  outstanding: zod.number(),
  totalBilled: zod.number(),
  invoiceCount: zod.number(),
  billCount: zod.number(),
});

/**
 * @summary List chart of accounts
 */
export const ListAccountsQueryParams = zod.object({
  type: zod
    .enum(["asset", "liability", "equity", "revenue", "expense"])
    .optional(),
});

export const ListAccountsResponseItem = zod.object({
  id: zod.number(),
  code: zod.string(),
  name: zod.string(),
  type: zod.enum(["asset", "liability", "equity", "revenue", "expense"]),
  description: zod.string().optional(),
  balance: zod.number(),
  isActive: zod.boolean(),
  createdAt: zod.coerce.date(),
});
export const ListAccountsResponse = zod.array(ListAccountsResponseItem);

/**
 * @summary Create an account
 */
export const CreateAccountBody = zod.object({
  code: zod.string(),
  name: zod.string(),
  type: zod.enum(["asset", "liability", "equity", "revenue", "expense"]),
  description: zod.string().optional(),
});

/**
 * @summary Get an account
 */
export const GetAccountParams = zod.object({
  id: zod.coerce.number(),
});

export const GetAccountResponse = zod.object({
  id: zod.number(),
  code: zod.string(),
  name: zod.string(),
  type: zod.enum(["asset", "liability", "equity", "revenue", "expense"]),
  description: zod.string().optional(),
  balance: zod.number(),
  isActive: zod.boolean(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update an account
 */
export const UpdateAccountParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateAccountBody = zod.object({
  code: zod.string(),
  name: zod.string(),
  type: zod.enum(["asset", "liability", "equity", "revenue", "expense"]),
  description: zod.string().optional(),
});

export const UpdateAccountResponse = zod.object({
  id: zod.number(),
  code: zod.string(),
  name: zod.string(),
  type: zod.enum(["asset", "liability", "equity", "revenue", "expense"]),
  description: zod.string().optional(),
  balance: zod.number(),
  isActive: zod.boolean(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete an account
 */
export const DeleteAccountParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List invoices
 */
export const ListInvoicesQueryParams = zod.object({
  status: zod.enum(["draft", "sent", "paid", "overdue", "voided"]).optional(),
  contactId: zod.coerce.number().optional(),
  search: zod.coerce.string().optional(),
});

export const ListInvoicesResponseItem = zod.object({
  id: zod.number(),
  invoiceNumber: zod.string(),
  contactId: zod.number(),
  contactName: zod.string().optional(),
  status: zod.enum(["draft", "sent", "paid", "overdue", "voided"]),
  issueDate: zod.coerce.date(),
  dueDate: zod.coerce.date(),
  subtotal: zod.number(),
  taxAmount: zod.number(),
  total: zod.number(),
  amountDue: zod.number(),
  reference: zod.string().optional(),
  notes: zod.string().optional(),
  lineItems: zod.array(
    zod.object({
      id: zod.number(),
      description: zod.string(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      accountId: zod.number().optional(),
      taxRate: zod.number().optional(),
      lineTotal: zod.number(),
    }),
  ),
  createdAt: zod.coerce.date(),
});
export const ListInvoicesResponse = zod.array(ListInvoicesResponseItem);

/**
 * @summary Create an invoice
 */
export const CreateInvoiceBody = zod.object({
  contactId: zod.number(),
  issueDate: zod.coerce.date(),
  dueDate: zod.coerce.date(),
  reference: zod.string().optional(),
  notes: zod.string().optional(),
  lineItems: zod.array(
    zod.object({
      description: zod.string(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      accountId: zod.number().optional(),
      taxRate: zod.number().optional(),
    }),
  ),
});

/**
 * @summary Get an invoice
 */
export const GetInvoiceParams = zod.object({
  id: zod.coerce.number(),
});

export const GetInvoiceResponse = zod.object({
  id: zod.number(),
  invoiceNumber: zod.string(),
  contactId: zod.number(),
  contactName: zod.string().optional(),
  status: zod.enum(["draft", "sent", "paid", "overdue", "voided"]),
  issueDate: zod.coerce.date(),
  dueDate: zod.coerce.date(),
  subtotal: zod.number(),
  taxAmount: zod.number(),
  total: zod.number(),
  amountDue: zod.number(),
  reference: zod.string().optional(),
  notes: zod.string().optional(),
  lineItems: zod.array(
    zod.object({
      id: zod.number(),
      description: zod.string(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      accountId: zod.number().optional(),
      taxRate: zod.number().optional(),
      lineTotal: zod.number(),
    }),
  ),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update an invoice
 */
export const UpdateInvoiceParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateInvoiceBody = zod.object({
  contactId: zod.number(),
  issueDate: zod.coerce.date(),
  dueDate: zod.coerce.date(),
  reference: zod.string().optional(),
  notes: zod.string().optional(),
  lineItems: zod.array(
    zod.object({
      description: zod.string(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      accountId: zod.number().optional(),
      taxRate: zod.number().optional(),
    }),
  ),
});

export const UpdateInvoiceResponse = zod.object({
  id: zod.number(),
  invoiceNumber: zod.string(),
  contactId: zod.number(),
  contactName: zod.string().optional(),
  status: zod.enum(["draft", "sent", "paid", "overdue", "voided"]),
  issueDate: zod.coerce.date(),
  dueDate: zod.coerce.date(),
  subtotal: zod.number(),
  taxAmount: zod.number(),
  total: zod.number(),
  amountDue: zod.number(),
  reference: zod.string().optional(),
  notes: zod.string().optional(),
  lineItems: zod.array(
    zod.object({
      id: zod.number(),
      description: zod.string(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      accountId: zod.number().optional(),
      taxRate: zod.number().optional(),
      lineTotal: zod.number(),
    }),
  ),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Void/delete an invoice
 */
export const DeleteInvoiceParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Mark invoice as sent
 */
export const SendInvoiceParams = zod.object({
  id: zod.coerce.number(),
});

export const SendInvoiceResponse = zod.object({
  id: zod.number(),
  invoiceNumber: zod.string(),
  contactId: zod.number(),
  contactName: zod.string().optional(),
  status: zod.enum(["draft", "sent", "paid", "overdue", "voided"]),
  issueDate: zod.coerce.date(),
  dueDate: zod.coerce.date(),
  subtotal: zod.number(),
  taxAmount: zod.number(),
  total: zod.number(),
  amountDue: zod.number(),
  reference: zod.string().optional(),
  notes: zod.string().optional(),
  lineItems: zod.array(
    zod.object({
      id: zod.number(),
      description: zod.string(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      accountId: zod.number().optional(),
      taxRate: zod.number().optional(),
      lineTotal: zod.number(),
    }),
  ),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Invoice statistics (total by status)
 */
export const GetInvoiceStatsResponse = zod.object({
  draft: zod.number(),
  sent: zod.number(),
  paid: zod.number(),
  overdue: zod.number(),
  voided: zod.number(),
  totalOutstanding: zod.number(),
});

/**
 * @summary List bills
 */
export const ListBillsQueryParams = zod.object({
  status: zod
    .enum(["draft", "awaiting_payment", "paid", "overdue", "voided"])
    .optional(),
  contactId: zod.coerce.number().optional(),
});

export const ListBillsResponseItem = zod.object({
  id: zod.number(),
  billNumber: zod.string(),
  contactId: zod.number(),
  contactName: zod.string().optional(),
  status: zod.enum(["draft", "awaiting_payment", "paid", "overdue", "voided"]),
  issueDate: zod.coerce.date(),
  dueDate: zod.coerce.date(),
  subtotal: zod.number(),
  taxAmount: zod.number(),
  total: zod.number(),
  amountDue: zod.number(),
  reference: zod.string().optional(),
  notes: zod.string().optional(),
  lineItems: zod.array(
    zod.object({
      id: zod.number(),
      description: zod.string(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      accountId: zod.number().optional(),
      taxRate: zod.number().optional(),
      lineTotal: zod.number(),
    }),
  ),
  createdAt: zod.coerce.date(),
});
export const ListBillsResponse = zod.array(ListBillsResponseItem);

/**
 * @summary Create a bill
 */
export const CreateBillBody = zod.object({
  contactId: zod.number(),
  issueDate: zod.coerce.date(),
  dueDate: zod.coerce.date(),
  reference: zod.string().optional(),
  notes: zod.string().optional(),
  lineItems: zod.array(
    zod.object({
      description: zod.string(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      accountId: zod.number().optional(),
      taxRate: zod.number().optional(),
    }),
  ),
});

/**
 * @summary Get a bill
 */
export const GetBillParams = zod.object({
  id: zod.coerce.number(),
});

export const GetBillResponse = zod.object({
  id: zod.number(),
  billNumber: zod.string(),
  contactId: zod.number(),
  contactName: zod.string().optional(),
  status: zod.enum(["draft", "awaiting_payment", "paid", "overdue", "voided"]),
  issueDate: zod.coerce.date(),
  dueDate: zod.coerce.date(),
  subtotal: zod.number(),
  taxAmount: zod.number(),
  total: zod.number(),
  amountDue: zod.number(),
  reference: zod.string().optional(),
  notes: zod.string().optional(),
  lineItems: zod.array(
    zod.object({
      id: zod.number(),
      description: zod.string(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      accountId: zod.number().optional(),
      taxRate: zod.number().optional(),
      lineTotal: zod.number(),
    }),
  ),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update a bill
 */
export const UpdateBillParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateBillBody = zod.object({
  contactId: zod.number(),
  issueDate: zod.coerce.date(),
  dueDate: zod.coerce.date(),
  reference: zod.string().optional(),
  notes: zod.string().optional(),
  lineItems: zod.array(
    zod.object({
      description: zod.string(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      accountId: zod.number().optional(),
      taxRate: zod.number().optional(),
    }),
  ),
});

export const UpdateBillResponse = zod.object({
  id: zod.number(),
  billNumber: zod.string(),
  contactId: zod.number(),
  contactName: zod.string().optional(),
  status: zod.enum(["draft", "awaiting_payment", "paid", "overdue", "voided"]),
  issueDate: zod.coerce.date(),
  dueDate: zod.coerce.date(),
  subtotal: zod.number(),
  taxAmount: zod.number(),
  total: zod.number(),
  amountDue: zod.number(),
  reference: zod.string().optional(),
  notes: zod.string().optional(),
  lineItems: zod.array(
    zod.object({
      id: zod.number(),
      description: zod.string(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      accountId: zod.number().optional(),
      taxRate: zod.number().optional(),
      lineTotal: zod.number(),
    }),
  ),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete a bill
 */
export const DeleteBillParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List payments
 */
export const ListPaymentsResponseItem = zod.object({
  id: zod.number(),
  type: zod.enum(["invoice_payment", "bill_payment"]),
  invoiceId: zod.number().optional(),
  billId: zod.number().optional(),
  bankAccountId: zod.number().optional(),
  amount: zod.number(),
  date: zod.coerce.date(),
  reference: zod.string().optional(),
  createdAt: zod.coerce.date(),
});
export const ListPaymentsResponse = zod.array(ListPaymentsResponseItem);

/**
 * @summary Create a payment
 */
export const CreatePaymentBody = zod.object({
  type: zod.enum(["invoice_payment", "bill_payment"]),
  invoiceId: zod.number().optional(),
  billId: zod.number().optional(),
  bankAccountId: zod.number().optional(),
  amount: zod.number(),
  date: zod.coerce.date(),
  reference: zod.string().optional(),
});

/**
 * @summary Get a payment
 */
export const GetPaymentParams = zod.object({
  id: zod.coerce.number(),
});

export const GetPaymentResponse = zod.object({
  id: zod.number(),
  type: zod.enum(["invoice_payment", "bill_payment"]),
  invoiceId: zod.number().optional(),
  billId: zod.number().optional(),
  bankAccountId: zod.number().optional(),
  amount: zod.number(),
  date: zod.coerce.date(),
  reference: zod.string().optional(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete a payment
 */
export const DeletePaymentParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List bank accounts
 */
export const ListBankAccountsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  accountNumber: zod.string().optional(),
  bankName: zod.string(),
  currency: zod.string(),
  balance: zod.number(),
  isActive: zod.boolean(),
  createdAt: zod.coerce.date(),
});
export const ListBankAccountsResponse = zod.array(ListBankAccountsResponseItem);

/**
 * @summary Create a bank account
 */
export const CreateBankAccountBody = zod.object({
  name: zod.string(),
  accountNumber: zod.string().optional(),
  bankName: zod.string(),
  currency: zod.string(),
});

/**
 * @summary Get a bank account
 */
export const GetBankAccountParams = zod.object({
  id: zod.coerce.number(),
});

export const GetBankAccountResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  accountNumber: zod.string().optional(),
  bankName: zod.string(),
  currency: zod.string(),
  balance: zod.number(),
  isActive: zod.boolean(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update a bank account
 */
export const UpdateBankAccountParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateBankAccountBody = zod.object({
  name: zod.string(),
  accountNumber: zod.string().optional(),
  bankName: zod.string(),
  currency: zod.string(),
});

export const UpdateBankAccountResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  accountNumber: zod.string().optional(),
  bankName: zod.string(),
  currency: zod.string(),
  balance: zod.number(),
  isActive: zod.boolean(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete a bank account
 */
export const DeleteBankAccountParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List bank transactions
 */
export const ListBankTransactionsQueryParams = zod.object({
  bankAccountId: zod.coerce.number().optional(),
  reconciled: zod.coerce.boolean().optional(),
});

export const ListBankTransactionsResponseItem = zod.object({
  id: zod.number(),
  bankAccountId: zod.number(),
  date: zod.coerce.date(),
  description: zod.string(),
  amount: zod.number(),
  type: zod.enum(["credit", "debit"]),
  reconciled: zod.boolean(),
  paymentId: zod.number().optional(),
  createdAt: zod.coerce.date(),
});
export const ListBankTransactionsResponse = zod.array(
  ListBankTransactionsResponseItem,
);

/**
 * @summary Create a bank transaction
 */
export const CreateBankTransactionBody = zod.object({
  bankAccountId: zod.number(),
  date: zod.coerce.date(),
  description: zod.string(),
  amount: zod.number(),
  type: zod.enum(["credit", "debit"]),
  reconciled: zod.boolean().optional(),
});

/**
 * @summary Get a bank transaction
 */
export const GetBankTransactionParams = zod.object({
  id: zod.coerce.number(),
});

export const GetBankTransactionResponse = zod.object({
  id: zod.number(),
  bankAccountId: zod.number(),
  date: zod.coerce.date(),
  description: zod.string(),
  amount: zod.number(),
  type: zod.enum(["credit", "debit"]),
  reconciled: zod.boolean(),
  paymentId: zod.number().optional(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update a bank transaction
 */
export const UpdateBankTransactionParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateBankTransactionBody = zod.object({
  bankAccountId: zod.number(),
  date: zod.coerce.date(),
  description: zod.string(),
  amount: zod.number(),
  type: zod.enum(["credit", "debit"]),
  reconciled: zod.boolean().optional(),
});

export const UpdateBankTransactionResponse = zod.object({
  id: zod.number(),
  bankAccountId: zod.number(),
  date: zod.coerce.date(),
  description: zod.string(),
  amount: zod.number(),
  type: zod.enum(["credit", "debit"]),
  reconciled: zod.boolean(),
  paymentId: zod.number().optional(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Profit and Loss report
 */
export const GetProfitLossReportQueryParams = zod.object({
  from: zod.date().optional(),
  to: zod.date().optional(),
  compare: zod.enum(["none", "previousPeriod", "previousYear"]).optional(),
  breakdown: zod.enum(["none", "monthly"]).optional(),
});

export const GetProfitLossReportResponse = zod.object({
  from: zod.coerce.date(),
  to: zod.coerce.date(),
  compare: zod.enum(["none", "previousPeriod", "previousYear"]),
  priorFrom: zod.coerce.date().optional(),
  priorTo: zod.coerce.date().optional(),
  monthly: zod.boolean(),
  months: zod
    .array(
      zod.object({
        label: zod.string(),
        from: zod.coerce.date(),
        to: zod.coerce.date(),
      }),
    )
    .optional(),
  revenue: zod.object({
    label: zod.string(),
    accounts: zod.array(
      zod.object({
        accountId: zod.number(),
        code: zod.string(),
        name: zod.string(),
        current: zod.number(),
        prior: zod.number().optional(),
        variance: zod.number().optional(),
        variancePct: zod.number().nullish(),
        pctOfRevenue: zod.number(),
        monthly: zod
          .array(
            zod.object({
              label: zod.string(),
              value: zod.number(),
            }),
          )
          .optional(),
      }),
    ),
    total: zod.number(),
    priorTotal: zod.number().optional(),
    variance: zod.number().optional(),
    variancePct: zod.number().nullish(),
    monthlyTotals: zod
      .array(
        zod.object({
          label: zod.string(),
          value: zod.number(),
        }),
      )
      .optional(),
  }),
  costOfSales: zod.object({
    label: zod.string(),
    accounts: zod.array(
      zod.object({
        accountId: zod.number(),
        code: zod.string(),
        name: zod.string(),
        current: zod.number(),
        prior: zod.number().optional(),
        variance: zod.number().optional(),
        variancePct: zod.number().nullish(),
        pctOfRevenue: zod.number(),
        monthly: zod
          .array(
            zod.object({
              label: zod.string(),
              value: zod.number(),
            }),
          )
          .optional(),
      }),
    ),
    total: zod.number(),
    priorTotal: zod.number().optional(),
    variance: zod.number().optional(),
    variancePct: zod.number().nullish(),
    monthlyTotals: zod
      .array(
        zod.object({
          label: zod.string(),
          value: zod.number(),
        }),
      )
      .optional(),
  }),
  grossProfit: zod.object({
    current: zod.number(),
    prior: zod.number().optional(),
    variance: zod.number().optional(),
    variancePct: zod.number().nullish(),
  }),
  expenses: zod.object({
    label: zod.string(),
    accounts: zod.array(
      zod.object({
        accountId: zod.number(),
        code: zod.string(),
        name: zod.string(),
        current: zod.number(),
        prior: zod.number().optional(),
        variance: zod.number().optional(),
        variancePct: zod.number().nullish(),
        pctOfRevenue: zod.number(),
        monthly: zod
          .array(
            zod.object({
              label: zod.string(),
              value: zod.number(),
            }),
          )
          .optional(),
      }),
    ),
    total: zod.number(),
    priorTotal: zod.number().optional(),
    variance: zod.number().optional(),
    variancePct: zod.number().nullish(),
    monthlyTotals: zod
      .array(
        zod.object({
          label: zod.string(),
          value: zod.number(),
        }),
      )
      .optional(),
  }),
  netProfit: zod.object({
    current: zod.number(),
    prior: zod.number().optional(),
    variance: zod.number().optional(),
    variancePct: zod.number().nullish(),
  }),
  totalExpenses: zod.number().optional(),
  priorTotalExpenses: zod.number().optional(),
});

/**
 * @summary Balance Sheet report
 */
export const GetBalanceSheetReportQueryParams = zod.object({
  date: zod.date().optional(),
  compare: zod.enum(["none", "previousPeriod", "previousYear"]).optional(),
});

export const GetBalanceSheetReportResponse = zod.object({
  date: zod.coerce.date(),
  compare: zod.enum(["none", "previousPeriod", "previousYear"]),
  priorDate: zod.coerce.date().optional(),
  assets: zod.object({
    label: zod.string(),
    accounts: zod.array(
      zod.object({
        accountId: zod.number(),
        code: zod.string(),
        name: zod.string(),
        current: zod.number(),
        prior: zod.number().optional(),
        variance: zod.number().optional(),
        variancePct: zod.number().nullish(),
      }),
    ),
    total: zod.number(),
    priorTotal: zod.number().optional(),
  }),
  liabilities: zod.object({
    label: zod.string(),
    accounts: zod.array(
      zod.object({
        accountId: zod.number(),
        code: zod.string(),
        name: zod.string(),
        current: zod.number(),
        prior: zod.number().optional(),
        variance: zod.number().optional(),
        variancePct: zod.number().nullish(),
      }),
    ),
    total: zod.number(),
    priorTotal: zod.number().optional(),
  }),
  equity: zod.object({
    label: zod.string(),
    accounts: zod.array(
      zod.object({
        accountId: zod.number(),
        code: zod.string(),
        name: zod.string(),
        current: zod.number(),
        prior: zod.number().optional(),
        variance: zod.number().optional(),
        variancePct: zod.number().nullish(),
      }),
    ),
    total: zod.number(),
    priorTotal: zod.number().optional(),
  }),
  totals: zod.object({
    assets: zod.number(),
    liabilitiesAndEquity: zod.number(),
    difference: zod.number(),
    priorAssets: zod.number().optional(),
    priorLiabilitiesAndEquity: zod.number().optional(),
  }),
});

/**
 * @summary Trial Balance report
 */
export const GetTrialBalanceReportQueryParams = zod.object({
  from: zod.date().optional(),
  to: zod.date().optional(),
});

export const GetTrialBalanceReportResponse = zod.object({
  from: zod.coerce.date().nullish(),
  to: zod.coerce.date(),
  rows: zod.array(
    zod.object({
      accountId: zod.number(),
      code: zod.string(),
      name: zod.string(),
      type: zod.string(),
      openingDebit: zod.number(),
      openingCredit: zod.number(),
      periodDebit: zod.number(),
      periodCredit: zod.number(),
      closingDebit: zod.number(),
      closingCredit: zod.number(),
    }),
  ),
  totals: zod.object({
    openingDebit: zod.number(),
    openingCredit: zod.number(),
    periodDebit: zod.number(),
    periodCredit: zod.number(),
    closingDebit: zod.number(),
    closingCredit: zod.number(),
  }),
  balanced: zod.boolean(),
});

/**
 * @summary Cash Flow Statement (indirect method)
 */
export const GetCashFlowStatementQueryParams = zod.object({
  from: zod.date().optional(),
  to: zod.date().optional(),
  compare: zod.enum(["none", "previousPeriod", "previousYear"]).optional(),
});

export const GetCashFlowStatementResponse = zod.object({
  from: zod.coerce.date(),
  to: zod.coerce.date(),
  compare: zod.enum(["none", "previousPeriod", "previousYear"]),
  priorFrom: zod.coerce.date().optional(),
  priorTo: zod.coerce.date().optional(),
  operating: zod.object({
    label: zod.string(),
    lines: zod.array(
      zod.object({
        label: zod.string(),
        current: zod.number(),
        prior: zod.number().optional(),
        variance: zod.number().optional(),
        variancePct: zod.number().nullish(),
        accountId: zod.number().nullish(),
        accountIds: zod.array(zod.number()).optional(),
      }),
    ),
    total: zod.number(),
    priorTotal: zod.number().optional(),
  }),
  investing: zod.object({
    label: zod.string(),
    lines: zod.array(
      zod.object({
        label: zod.string(),
        current: zod.number(),
        prior: zod.number().optional(),
        variance: zod.number().optional(),
        variancePct: zod.number().nullish(),
        accountId: zod.number().nullish(),
        accountIds: zod.array(zod.number()).optional(),
      }),
    ),
    total: zod.number(),
    priorTotal: zod.number().optional(),
  }),
  financing: zod.object({
    label: zod.string(),
    lines: zod.array(
      zod.object({
        label: zod.string(),
        current: zod.number(),
        prior: zod.number().optional(),
        variance: zod.number().optional(),
        variancePct: zod.number().nullish(),
        accountId: zod.number().nullish(),
        accountIds: zod.array(zod.number()).optional(),
      }),
    ),
    total: zod.number(),
    priorTotal: zod.number().optional(),
  }),
  netChange: zod.object({
    current: zod.number(),
    prior: zod.number().optional(),
    variance: zod.number().optional(),
    variancePct: zod.number().nullish(),
  }),
  openingCash: zod.object({
    current: zod.number(),
    prior: zod.number().optional(),
    variance: zod.number().optional(),
    variancePct: zod.number().nullish(),
  }),
  closingCash: zod.object({
    current: zod.number(),
    prior: zod.number().optional(),
    variance: zod.number().optional(),
    variancePct: zod.number().nullish(),
  }),
  reconciliationDifference: zod.number(),
});

/**
 * @summary General Ledger
 */
export const GetGeneralLedgerReportQueryParams = zod.object({
  from: zod.date().optional(),
  to: zod.date().optional(),
  accountId: zod.coerce.number().optional(),
  page: zod.coerce.number().optional(),
  pageSize: zod.coerce.number().optional(),
});

export const GetGeneralLedgerReportResponseItem = zod.object({
  accountId: zod.number(),
  accountCode: zod.string(),
  accountName: zod.string(),
  accountType: zod.string(),
  openingBalance: zod.number(),
  totalDebit: zod.number(),
  totalCredit: zod.number(),
  closingBalance: zod.number(),
  totalLines: zod.number(),
  lines: zod.array(
    zod.object({
      entryId: zod.number(),
      entryNumber: zod.string(),
      date: zod.coerce.date(),
      narration: zod.string(),
      description: zod.string().nullish(),
      sourceType: zod.string().nullish(),
      sourceId: zod.number().nullish(),
      debit: zod.number(),
      credit: zod.number(),
      balance: zod.number(),
    }),
  ),
});
export const GetGeneralLedgerReportResponse = zod.array(
  GetGeneralLedgerReportResponseItem,
);

/**
 * @summary Drill into journal lines for an account in a period
 */
export const GetDrillAccountQueryParams = zod.object({
  accountId: zod.coerce.number(),
  from: zod.date().optional(),
  to: zod.date().optional(),
  page: zod.coerce.number().optional(),
  pageSize: zod.coerce.number().optional(),
});

export const GetDrillAccountResponse = zod.object({
  accountId: zod.number(),
  from: zod.coerce.date().nullish(),
  to: zod.coerce.date(),
  page: zod.number(),
  pageSize: zod.number(),
  totalLines: zod.number(),
  lines: zod.array(
    zod.object({
      entryId: zod.number(),
      entryNumber: zod.string(),
      date: zod.coerce.date(),
      narration: zod.string(),
      description: zod.string().nullish(),
      sourceType: zod.string().nullish(),
      sourceId: zod.number().nullish(),
      debit: zod.number(),
      credit: zod.number(),
      balance: zod.number(),
    }),
  ),
});

/**
 * @summary Resolve a sourceType+sourceId to its document and journal entries
 */
export const GetDrillSourceQueryParams = zod.object({
  sourceType: zod.coerce.string(),
  sourceId: zod.coerce.number(),
});

export const GetDrillSourceResponse = zod.object({
  sourceType: zod.string(),
  sourceId: zod.number(),
  document: zod
    .unknown()
    .nullish()
    .describe("Source document payload (shape depends on sourceType)."),
  journalEntries: zod.array(zod.record(zod.string(), zod.unknown())),
});
