/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { BalanceSheetReportTotals } from "./balanceSheetReportTotals";
import type { BSSection } from "./bSSection";
import type { CompareMode } from "./compareMode";

export interface BalanceSheetReport {
  date: Date;
  compare: CompareMode;
  priorDate?: Date;
  assets: BSSection;
  liabilities: BSSection;
  equity: BSSection;
  totals: BalanceSheetReportTotals;
}
