/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { BankTransactionType } from "./bankTransactionType";
export interface BankTransaction {
    id: number;
    bankAccountId: number;
    date: Date;
    description: string;
    amount: number;
    type: BankTransactionType;
    reconciled: boolean;
    paymentId?: number;
    createdAt: Date;
}
//# sourceMappingURL=bankTransaction.d.ts.map