/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type BankTransactionType = (typeof BankTransactionType)[keyof typeof BankTransactionType];
export declare const BankTransactionType: {
    readonly credit: "credit";
    readonly debit: "debit";
};
//# sourceMappingURL=bankTransactionType.d.ts.map