/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */

export type BillStatus = (typeof BillStatus)[keyof typeof BillStatus];

export const BillStatus = {
  draft: "draft",
  awaiting_payment: "awaiting_payment",
  paid: "paid",
  overdue: "overdue",
  voided: "voided",
} as const;
