/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type BillStatus = (typeof BillStatus)[keyof typeof BillStatus];
export declare const BillStatus: {
    readonly draft: "draft";
    readonly awaiting_payment: "awaiting_payment";
    readonly paid: "paid";
    readonly overdue: "overdue";
    readonly voided: "voided";
};
//# sourceMappingURL=billStatus.d.ts.map