/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { BillLineItem } from "./billLineItem";
import type { BillStatus } from "./billStatus";
export interface Bill {
    id: number;
    billNumber: string;
    contactId: number;
    contactName?: string;
    status: BillStatus;
    issueDate: Date;
    dueDate: Date;
    subtotal: number;
    taxAmount: number;
    total: number;
    amountDue: number;
    reference?: string;
    notes?: string;
    lineItems: BillLineItem[];
    createdAt: Date;
}
//# sourceMappingURL=bill.d.ts.map