/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export interface BSAccountRow {
    accountId: number;
    code: string;
    name: string;
    current: number;
    prior?: number;
    variance?: number;
    variancePct?: number | null;
}
//# sourceMappingURL=bSAccountRow.d.ts.map