/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { BSAccountRow } from "./bSAccountRow";

export interface BSSection {
  label: string;
  accounts: BSAccountRow[];
  total: number;
  priorTotal?: number;
}
