/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { CashFlowSection } from "./cashFlowSection";
import type { CompareMode } from "./compareMode";
import type { ScalarComparison } from "./scalarComparison";

export interface CashFlowStatement {
  from: Date;
  to: Date;
  compare: CompareMode;
  priorFrom?: Date;
  priorTo?: Date;
  operating: CashFlowSection;
  investing: CashFlowSection;
  financing: CashFlowSection;
  netChange: ScalarComparison;
  openingCash: ScalarComparison;
  closingCash: ScalarComparison;
  reconciliationDifference: number;
}
