/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */

export type CompareMode = (typeof CompareMode)[keyof typeof CompareMode];

export const CompareMode = {
  none: "none",
  previousPeriod: "previousPeriod",
  previousYear: "previousYear",
} as const;
