/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { ContactType } from "./contactType";

export interface Contact {
  id: number;
  name: string;
  email?: string;
  phone?: string;
  type: ContactType;
  address?: string;
  city?: string;
  country?: string;
  taxNumber?: string;
  accountNumber?: string;
  isActive: boolean;
  createdAt: Date;
}
