/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export interface ContactSummary {
    contactId: number;
    totalInvoiced: number;
    totalPaid: number;
    outstanding: number;
    totalBilled: number;
    invoiceCount: number;
    billCount: number;
}
//# sourceMappingURL=contactSummary.d.ts.map