/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type ContactType = (typeof ContactType)[keyof typeof ContactType];
export declare const ContactType: {
    readonly customer: "customer";
    readonly supplier: "supplier";
    readonly both: "both";
};
//# sourceMappingURL=contactType.d.ts.map