/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateInvoiceLineItemBody {
  description: string;
  quantity: number;
  unitPrice: number;
  accountId?: number;
  taxRate?: number;
}
