/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */

export type CreateAccountBodyType =
  (typeof CreateAccountBodyType)[keyof typeof CreateAccountBodyType];

export const CreateAccountBodyType = {
  asset: "asset",
  liability: "liability",
  equity: "equity",
  revenue: "revenue",
  expense: "expense",
} as const;
