/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type CreateBankTransactionBodyType = (typeof CreateBankTransactionBodyType)[keyof typeof CreateBankTransactionBodyType];
export declare const CreateBankTransactionBodyType: {
    readonly credit: "credit";
    readonly debit: "debit";
};
//# sourceMappingURL=createBankTransactionBodyType.d.ts.map