/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type CreateContactBodyType = (typeof CreateContactBodyType)[keyof typeof CreateContactBodyType];
export declare const CreateContactBodyType: {
    readonly customer: "customer";
    readonly supplier: "supplier";
    readonly both: "both";
};
//# sourceMappingURL=createContactBodyType.d.ts.map