/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */

export type CreateBankTransactionBodyType =
  (typeof CreateBankTransactionBodyType)[keyof typeof CreateBankTransactionBodyType];

export const CreateBankTransactionBodyType = {
  credit: "credit",
  debit: "debit",
} as const;
