/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type CreateAccountBodyType = (typeof CreateAccountBodyType)[keyof typeof CreateAccountBodyType];
export declare const CreateAccountBodyType: {
    readonly asset: "asset";
    readonly liability: "liability";
    readonly equity: "equity";
    readonly revenue: "revenue";
    readonly expense: "expense";
};
//# sourceMappingURL=createAccountBodyType.d.ts.map