/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateBillLineItemBody } from "./createBillLineItemBody";
export interface CreateBillBody {
    contactId: number;
    issueDate: Date;
    dueDate: Date;
    reference?: string;
    notes?: string;
    lineItems: CreateBillLineItemBody[];
}
//# sourceMappingURL=createBillBody.d.ts.map