/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateInvoiceLineItemBody } from "./createInvoiceLineItemBody";

export interface CreateInvoiceBody {
  contactId: number;
  issueDate: Date;
  dueDate: Date;
  reference?: string;
  notes?: string;
  lineItems: CreateInvoiceLineItemBody[];
}
