/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateBankTransactionBodyType } from "./createBankTransactionBodyType";
export interface CreateBankTransactionBody {
    bankAccountId: number;
    date: Date;
    description: string;
    amount: number;
    type: CreateBankTransactionBodyType;
    reconciled?: boolean;
}
//# sourceMappingURL=createBankTransactionBody.d.ts.map