/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { CreatePaymentBodyType } from "./createPaymentBodyType";

export interface CreatePaymentBody {
  type: CreatePaymentBodyType;
  invoiceId?: number;
  billId?: number;
  bankAccountId?: number;
  amount: number;
  date: Date;
  reference?: string;
}
