/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */

export type CreatePaymentBodyType =
  (typeof CreatePaymentBodyType)[keyof typeof CreatePaymentBodyType];

export const CreatePaymentBodyType = {
  invoice_payment: "invoice_payment",
  bill_payment: "bill_payment",
} as const;
