/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateContactBodyType } from "./createContactBodyType";

export interface CreateContactBody {
  name: string;
  email?: string;
  phone?: string;
  type: CreateContactBodyType;
  address?: string;
  city?: string;
  country?: string;
  taxNumber?: string;
  accountNumber?: string;
}
