/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export interface DashboardSummary {
    totalReceivable: number;
    totalPayable: number;
    cashBalance: number;
    overdueInvoices: number;
    overdueBills: number;
    totalRevenue: number;
    totalExpenses: number;
    netProfit: number;
}
//# sourceMappingURL=dashboardSummary.d.ts.map