/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { GeneralLedgerLine } from "./generalLedgerLine";
export interface DrillAccountResponse {
    accountId: number;
    from?: Date | null;
    to: Date;
    page: number;
    pageSize: number;
    totalLines: number;
    lines: GeneralLedgerLine[];
}
//# sourceMappingURL=drillAccountResponse.d.ts.map