/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */

export interface GeneralLedgerLine {
  entryId: number;
  entryNumber: string;
  date: Date;
  narration: string;
  description?: string | null;
  sourceType?: string | null;
  sourceId?: number | null;
  debit: number;
  credit: number;
  balance: number;
}
