/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { GeneralLedgerAccount } from "./generalLedgerAccount";
export interface GeneralLedgerReport {
    from: Date;
    to: Date;
    page?: number;
    pageSize?: number;
    accounts: GeneralLedgerAccount[];
}
//# sourceMappingURL=generalLedgerReport.d.ts.map