/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { CompareMode } from "./compareMode";
export type GetBalanceSheetReportParams = {
    date?: Date;
    compare?: CompareMode;
};
//# sourceMappingURL=getBalanceSheetReportParams.d.ts.map