/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type GetDrillSourceParams = {
    sourceType: string;
    sourceId: number;
};
//# sourceMappingURL=getDrillSourceParams.d.ts.map