/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */

export type GetDrillAccountParams = {
  accountId: number;
  from?: Date;
  to?: Date;
  page?: number;
  pageSize?: number;
};
