/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type GetGeneralLedgerReportParams = {
    from?: Date;
    to?: Date;
    accountId?: number;
    page?: number;
    pageSize?: number;
};
//# sourceMappingURL=getGeneralLedgerReportParams.d.ts.map