/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */

export type GetProfitLossReportBreakdown =
  (typeof GetProfitLossReportBreakdown)[keyof typeof GetProfitLossReportBreakdown];

export const GetProfitLossReportBreakdown = {
  none: "none",
  monthly: "monthly",
} as const;
