/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { CompareMode } from "./compareMode";
import type { GetProfitLossReportBreakdown } from "./getProfitLossReportBreakdown";
export type GetProfitLossReportParams = {
    from?: Date;
    to?: Date;
    compare?: CompareMode;
    breakdown?: GetProfitLossReportBreakdown;
};
//# sourceMappingURL=getProfitLossReportParams.d.ts.map