/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { InvoiceLineItem } from "./invoiceLineItem";
import type { InvoiceStatus } from "./invoiceStatus";
export interface Invoice {
    id: number;
    invoiceNumber: string;
    contactId: number;
    contactName?: string;
    status: InvoiceStatus;
    issueDate: Date;
    dueDate: Date;
    subtotal: number;
    taxAmount: number;
    total: number;
    amountDue: number;
    reference?: string;
    notes?: string;
    lineItems: InvoiceLineItem[];
    createdAt: Date;
}
//# sourceMappingURL=invoice.d.ts.map