/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */

export interface InvoiceStats {
  draft: number;
  sent: number;
  paid: number;
  overdue: number;
  voided: number;
  totalOutstanding: number;
}
