/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { ListBillsStatus } from "./listBillsStatus";

export type ListBillsParams = {
  status?: ListBillsStatus;
  contactId?: number;
};
