/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */

export type ListContactsType =
  (typeof ListContactsType)[keyof typeof ListContactsType];

export const ListContactsType = {
  customer: "customer",
  supplier: "supplier",
  both: "both",
} as const;
