/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type ListInvoicesStatus = (typeof ListInvoicesStatus)[keyof typeof ListInvoicesStatus];
export declare const ListInvoicesStatus: {
    readonly draft: "draft";
    readonly sent: "sent";
    readonly paid: "paid";
    readonly overdue: "overdue";
    readonly voided: "voided";
};
//# sourceMappingURL=listInvoicesStatus.d.ts.map