/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type ListBillsStatus = (typeof ListBillsStatus)[keyof typeof ListBillsStatus];
export declare const ListBillsStatus: {
    readonly draft: "draft";
    readonly awaiting_payment: "awaiting_payment";
    readonly paid: "paid";
    readonly overdue: "overdue";
    readonly voided: "voided";
};
//# sourceMappingURL=listBillsStatus.d.ts.map