/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { ListInvoicesStatus } from "./listInvoicesStatus";
export type ListInvoicesParams = {
    status?: ListInvoicesStatus;
    contactId?: number;
    search?: string;
};
//# sourceMappingURL=listInvoicesParams.d.ts.map