/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type ListAccountsType = (typeof ListAccountsType)[keyof typeof ListAccountsType];
export declare const ListAccountsType: {
    readonly asset: "asset";
    readonly liability: "liability";
    readonly equity: "equity";
    readonly revenue: "revenue";
    readonly expense: "expense";
};
//# sourceMappingURL=listAccountsType.d.ts.map