/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { PaymentType } from "./paymentType";

export interface Payment {
  id: number;
  type: PaymentType;
  invoiceId?: number;
  billId?: number;
  bankAccountId?: number;
  amount: number;
  date: Date;
  reference?: string;
  createdAt: Date;
}
