/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type PaymentType = (typeof PaymentType)[keyof typeof PaymentType];
export declare const PaymentType: {
    readonly invoice_payment: "invoice_payment";
    readonly bill_payment: "bill_payment";
};
//# sourceMappingURL=paymentType.d.ts.map