/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { PLAccountRowMonthlyItem } from "./pLAccountRowMonthlyItem";

export interface PLAccountRow {
  accountId: number;
  code: string;
  name: string;
  current: number;
  prior?: number;
  variance?: number;
  variancePct?: number | null;
  pctOfRevenue: number;
  monthly?: PLAccountRowMonthlyItem[];
}
