/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { PLAccountRow } from "./pLAccountRow";
import type { PLSectionMonthlyTotalsItem } from "./pLSectionMonthlyTotalsItem";

export interface PLSection {
  label: string;
  accounts: PLAccountRow[];
  total: number;
  priorTotal?: number;
  variance?: number;
  variancePct?: number | null;
  monthlyTotals?: PLSectionMonthlyTotalsItem[];
}
