/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export type ProfitLossReportMonthsItem = {
    label: string;
    from: Date;
    to: Date;
};
//# sourceMappingURL=profitLossReportMonthsItem.d.ts.map