/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { CompareMode } from "./compareMode";
import type { PLSection } from "./pLSection";
import type { ProfitLossReportMonthsItem } from "./profitLossReportMonthsItem";
import type { ScalarComparison } from "./scalarComparison";

export interface ProfitLossReport {
  from: Date;
  to: Date;
  compare: CompareMode;
  priorFrom?: Date;
  priorTo?: Date;
  monthly: boolean;
  months?: ProfitLossReportMonthsItem[];
  revenue: PLSection;
  costOfSales: PLSection;
  grossProfit: ScalarComparison;
  expenses: PLSection;
  netProfit: ScalarComparison;
  totalExpenses?: number;
  priorTotalExpenses?: number;
}
