/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { ReportSectionAccountsItem } from "./reportSectionAccountsItem";
export interface ReportSection {
    label: string;
    accounts: ReportSectionAccountsItem[];
    total: number;
}
//# sourceMappingURL=reportSection.d.ts.map