/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
import type { TrialBalanceReportTotals } from "./trialBalanceReportTotals";
import type { TrialBalanceRow } from "./trialBalanceRow";
export interface TrialBalanceReport {
    from?: Date | null;
    to: Date;
    rows: TrialBalanceRow[];
    totals: TrialBalanceReportTotals;
    balanced: boolean;
}
//# sourceMappingURL=trialBalanceReport.d.ts.map