/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export interface TrialBalanceRow {
    accountId: number;
    code: string;
    name: string;
    type: string;
    openingDebit: number;
    openingCredit: number;
    periodDebit: number;
    periodCredit: number;
    closingDebit: number;
    closingCredit: number;
}
//# sourceMappingURL=trialBalanceRow.d.ts.map