/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Accounting System API
 * OpenAPI spec version: 0.1.0
 */
export interface TrialBalanceLine {
    code: string;
    name: string;
    type: string;
    debit: number;
    credit: number;
}
//# sourceMappingURL=trialBalanceLine.d.ts.map